name: Deploy Staging to Cpanel Action
on:
  push:
    branches:
    - staging
jobs:
  Staging-Deploy-Action:
    name: Staging-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
      with:
        fetch-depth: 2
    - name: Staging-Deploy-Action
      uses: rehandotwork/Staging-Deploy-Action@v1.1.0
      with:
        ftp-server: ${{ secret.FTP_SERVER }}
        ftp-username: ${{ secret.FTP_USERNAME }}
        fpt-password: ${{ secret.FTP_PASSWORD }}
