name: Deploy Staging to Cpanel Action
on:
  push:
    branches:
    - staging
jobs:
  Staging-Deploy-Action:
    name: Staging-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
      with:
        fetch-depth: 2
    - name: Staging-Deploy-Action
      uses: rehandotwork/aben@v1.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        fpt-password: ${{ secrets.FTP_PASSWORD }}
